"""RAG pre-filter for large product catalogs.

Reduces a catalog of ~3000 products to ~100-150 relevant items using
multimodal embeddings (generated by build_catalog.py) before the curation
LLM prompt. Small catalogs (≤150 items) bypass this entirely.

Usage (called from generate_curation.py):
    from rag_filter import filter_catalog
    filtered = filter_catalog(catalog, plan_css, products_dir, vibe, 150, verbose)
"""

import json
import math
import os
import re
from pathlib import Path


def cosine_similarity(a, b):
    """Compute cosine similarity between two vectors."""
    dot = sum(x * y for x, y in zip(a, b))
    norm_a = math.sqrt(sum(x * x for x in a))
    norm_b = math.sqrt(sum(x * x for x in b))
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return dot / (norm_a * norm_b)


def load_embeddings(products_dir):
    """Load product embeddings from products source directory.

    Returns {item_no: embedding_vector} or None if nothing found.
    """
    products_dir = Path(products_dir)

    # Try merged catalog file first
    merged_path = products_dir / "catalog.embeddings.json"
    if merged_path.exists():
        data = json.loads(merged_path.read_text(encoding="utf-8"))
        return {item_no: entry["embedding"] for item_no, entry in data.items()
                if "embedding" in entry}

    # Fallback: glob per-product embedding files and merge in-memory
    emb_files = sorted(products_dir.glob("*.embeddings.json"))
    if not emb_files:
        return None

    embeddings = {}
    for path in emb_files:
        if path.stem == "catalog":
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        item_no = data.get("item_no")
        if item_no and "embedding" in data:
            embeddings[str(item_no)] = data["embedding"]

    return embeddings if embeddings else None


def embed_text(text):
    """Embed a plain text string via Gemini embed_content API.

    Returns list[float] or None on failure.
    """
    from build_catalog import EMBEDDING_MODEL, EMBEDDING_DIMENSIONS

    try:
        from google import genai
        from google.genai import types as genai_types
    except ImportError:
        print("  RAG: google-genai SDK not installed, skipping")
        return None

    from llm_utils import _load_dotenv
    _load_dotenv()

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("  RAG: GEMINI_API_KEY not set, skipping")
        return None

    client = genai.Client(api_key=api_key)
    try:
        response = client.models.embed_content(
            model=EMBEDDING_MODEL,
            contents=[text],
            config=genai_types.EmbedContentConfig(
                output_dimensionality=EMBEDDING_DIMENSIONS,
            ),
        )
    except Exception as e:
        print(f"  RAG: embed_text error: {e}")
        return None

    if response.embeddings and response.embeddings[0].values:
        return list(response.embeddings[0].values)
    return None


def parse_room_names(plan_css):
    """Extract {room_id: room_name} from CSS comments.

    Parses patterns like: #r1.room { ... /* Living Room */ }
    Deduplicates multi-component rooms (r1_0, r1_1 → r1).
    """
    rooms = {}
    for m in re.finditer(
        r"#(r\d+(?:_\d+)?)\.room\s*\{[^}]*?/\*\s*(.+?)\s*\*/", plan_css
    ):
        room_id = re.sub(r"_\d+$", "", m.group(1))
        if room_id not in rooms:
            rooms[room_id] = m.group(2)
    return rooms


def vibe_filter(embeddings, vibe, top_n=500):
    """Stage 1: rank all products by similarity to vibe string, keep top_n.

    If no vibe provided, returns all item_nos (passthrough).
    """
    if not vibe:
        return set(embeddings.keys())

    vibe_vec = embed_text(vibe)
    if vibe_vec is None:
        return set(embeddings.keys())

    scored = []
    for item_no, emb in embeddings.items():
        scored.append((item_no, cosine_similarity(vibe_vec, emb)))

    scored.sort(key=lambda x: x[1], reverse=True)
    return {item_no for item_no, _ in scored[:top_n]}


def _build_profile_lookups(profiles):
    """Build item_no -> (placement, tier, category) lookups from profiles."""
    placement_lookup = {}
    tier_lookup = {}
    cat_lookup = {}
    for prof in profiles:
        item_no = str(prof.get("item_no", ""))
        placement_lookup[item_no] = prof.get("placement", "floor")
        tier_lookup[item_no] = prof.get("tier", "accent")
        cats = prof.get("categories", [])
        cat_lookup[item_no] = cats[0] if cats else "other"
    return placement_lookup, tier_lookup, cat_lookup


# Minimum items per tier in final result (coarse — avoids starving the LLM)
_TIER_FLOOR = {"anchor": 8, "accent": 8, "fill": 5}


def room_filter(survivors, embeddings, profiles, room_names, vibe, target_total=150):
    """Stage 2: per-room hybrid filtering (hard metadata + semantic ranking).

    Hard filters: buckets by (placement, category) compound key to guarantee
    all placement types (floor/wall/surface) are represented. Tier floor
    ensures anchors, accents, and fills all survive.

    Semantic: within each bucket, items are ranked by cosine similarity to
    "{room_name} {vibe}" embedding.
    """
    if not room_names:
        return survivors

    placement_lookup, tier_lookup, cat_lookup = _build_profile_lookups(profiles)

    # Compound bucket key: (placement, category) — guarantees placement diversity
    def bucket_key(item_no):
        return (placement_lookup.get(item_no, "floor"),
                cat_lookup.get(item_no, "other"))

    # Count distinct buckets among survivors
    buckets = set()
    for item_no in survivors:
        buckets.add(bucket_key(item_no))

    num_rooms = max(len(room_names), 1)
    num_buckets = max(len(buckets), 1)
    per_bucket = max(target_total // num_rooms // num_buckets, 2)

    result = set()

    for room_id, room_name in room_names.items():
        query = f"{room_name} {vibe}".strip()
        query_vec = embed_text(query)
        if query_vec is None:
            result.update(survivors)
            continue

        # Score survivors by semantic similarity
        scored = []
        for item_no in survivors:
            if item_no not in embeddings:
                continue
            scored.append((item_no, cosine_similarity(query_vec, embeddings[item_no])))

        scored.sort(key=lambda x: x[1], reverse=True)

        # (placement, category)-bucketed selection
        bucket_counts = {}
        for item_no, _ in scored:
            bk = bucket_key(item_no)
            bucket_counts.setdefault(bk, 0)
            if bucket_counts[bk] < per_bucket:
                result.add(item_no)
                bucket_counts[bk] += 1

    # Tier floor: ensure minimum representation per tier
    # Uses vibe embedding for ranking (already computed in vibe_filter stage)
    tier_counts = {}
    for item_no in result:
        t = tier_lookup.get(item_no, "accent")
        tier_counts[t] = tier_counts.get(t, 0) + 1

    for tier, floor in _TIER_FLOOR.items():
        deficit = floor - tier_counts.get(tier, 0)
        if deficit <= 0:
            continue
        # Pull top-scoring survivors of this tier not yet in result
        candidates = [(item_no, embeddings[item_no]) for item_no in survivors
                      if item_no in embeddings
                      and item_no not in result
                      and tier_lookup.get(item_no) == tier]
        if not candidates:
            continue
        # Score by vibe if available, otherwise just take first N
        vibe_vec = embed_text(vibe) if vibe else None
        if vibe_vec:
            candidates.sort(
                key=lambda x: cosine_similarity(vibe_vec, x[1]), reverse=True,
            )
        for item_no, _ in candidates[:deficit]:
            result.add(item_no)

    return result


def _score_filtered_out(filtered_out, embeddings, profiles, room_names, vibe):
    """Score filtered-out products by their best room similarity.

    Returns list of dicts sorted by score descending (near-misses first).
    """
    placement_lookup, tier_lookup, cat_lookup = _build_profile_lookups(profiles)

    # Build name lookup
    name_lookup = {}
    for prof in profiles:
        name_lookup[str(prof.get("item_no", ""))] = prof.get("item_no", "")

    # Embed each room query (reuses the same queries as room_filter)
    room_vecs = {}
    for room_id, room_name in room_names.items():
        query = f"{room_name} {vibe}".strip()
        vec = embed_text(query)
        if vec:
            room_vecs[room_id] = vec

    # Also embed vibe alone as fallback
    vibe_vec = embed_text(vibe) if vibe else None

    scored = []
    for item_no in filtered_out:
        if item_no not in embeddings:
            continue
        emb = embeddings[item_no]

        # Best score across all room queries
        best_score = 0.0
        best_room = None
        for room_id, vec in room_vecs.items():
            s = cosine_similarity(vec, emb)
            if s > best_score:
                best_score = s
                best_room = room_id

        # Vibe-only score
        vibe_score = cosine_similarity(vibe_vec, emb) if vibe_vec else None

        scored.append({
            "item_no": item_no,
            "placement": placement_lookup.get(item_no, "?"),
            "tier": tier_lookup.get(item_no, "?"),
            "category": cat_lookup.get(item_no, "?"),
            "best_room_score": round(best_score, 4),
            "best_room": best_room,
            "vibe_score": round(vibe_score, 4) if vibe_score is not None else None,
        })

    scored.sort(key=lambda x: x["best_room_score"], reverse=True)
    return scored


def filter_catalog(catalog, plan_css, products_dir, vibe="", target_total=150, verbose=False):
    """Main entry point: filter a large catalog down to ~target_total products.

    Returns (filtered_catalog, rag_report) or (None, None) on failure.
    filtered_catalog has the same structure as catalog (products, profiles, footprints).
    rag_report contains filter stats and scored list of filtered-out products.
    Products missing embeddings are included unconditionally.
    """
    products = catalog["products"]
    profiles = catalog.get("profiles", [])

    embeddings = load_embeddings(products_dir)
    if embeddings is None:
        print("  RAG: no embeddings found, falling back to full catalog")
        return None, None

    if verbose:
        print(f"  RAG: loaded {len(embeddings)} embeddings")

    # Identify products with and without embeddings
    all_item_nos = {str(p["item_no"]) for p in products}
    has_embedding = all_item_nos & set(embeddings.keys())
    no_embedding = all_item_nos - has_embedding

    if verbose and no_embedding:
        print(f"  RAG: {len(no_embedding)} products without embeddings (included unconditionally)")

    # Stage 1: vibe filter
    stage1 = vibe_filter(
        {k: v for k, v in embeddings.items() if k in has_embedding},
        vibe,
    )
    if verbose:
        print(f"  RAG: vibe filter: {len(has_embedding)} -> {len(stage1)}")

    # Stage 2: room-based category-bucketed filter
    room_names = parse_room_names(plan_css)
    if verbose:
        print(f"  RAG: rooms: {room_names}")

    # Adjust target to account for no-embedding products
    adjusted_target = max(target_total - len(no_embedding), 50)

    stage2 = room_filter(
        stage1, embeddings, profiles, room_names, vibe, adjusted_target,
    )

    # Build profile lookups for stats
    pl, tl, _ = _build_profile_lookups(profiles)

    if verbose:
        print(f"  RAG: room filter: {len(stage1)} -> {len(stage2)}")
        pl_counts = {}
        tl_counts = {}
        for item_no in stage2:
            p = pl.get(item_no, "?")
            t = tl.get(item_no, "?")
            pl_counts[p] = pl_counts.get(p, 0) + 1
            tl_counts[t] = tl_counts.get(t, 0) + 1
        print(f"  RAG: placement mix: {dict(sorted(pl_counts.items()))}")
        print(f"  RAG: tier mix: {dict(sorted(tl_counts.items()))}")

    # Combine: filtered + no-embedding products
    keep = stage2 | no_embedding
    filtered_out = has_embedding - keep

    # Slice catalog
    filtered_products = [p for p in products if str(p["item_no"]) in keep]
    filtered_profiles = [p for p in profiles if str(p.get("item_no", "")) in keep]
    filtered_footprints = []
    for fp in catalog.get("footprints", []):
        m = re.match(r"#i(\d+)", fp)
        if m and m.group(1) in keep:
            filtered_footprints.append(fp)

    # Build report: score filtered-out products (near-misses first)
    removed_scored = _score_filtered_out(
        filtered_out, embeddings, profiles, room_names, vibe,
    )

    # Survivor placement/tier stats
    surv_pl = {}
    surv_tl = {}
    for item_no in keep:
        surv_pl[pl.get(item_no, "?")] = surv_pl.get(pl.get(item_no, "?"), 0) + 1
        surv_tl[tl.get(item_no, "?")] = surv_tl.get(tl.get(item_no, "?"), 0) + 1

    rag_report = {
        "before": len(products),
        "after": len(filtered_products),
        "target": target_total,
        "vibe": vibe or None,
        "rooms": room_names,
        "stages": {
            "vibe_filter": {"in": len(has_embedding), "out": len(stage1)},
            "room_filter": {"in": len(stage1), "out": len(stage2)},
        },
        "survivors": {
            "placement": dict(sorted(surv_pl.items())),
            "tier": dict(sorted(surv_tl.items())),
        },
        "no_embedding": len(no_embedding),
        "filtered_out": removed_scored,
    }

    filtered_catalog = {
        "products": filtered_products,
        "profiles": filtered_profiles,
        "footprints": filtered_footprints,
    }

    return filtered_catalog, rag_report
